### ISSUE TITLE
貌似不支持自己的网站，出现了报错

### ISSUE THREAD

**Issue by koala9527** [lyc8503/UptimeFlare#1]
![image](https://github.com/lyc8503/UptimeFlare/assets/36888009/f2841b58-7a0c-48b1-8b2a-f1cc598f9ad7)

![image](https://github.com/lyc8503/UptimeFlare/assets/36888009/b4f1afd4-8808-4ea2-9552-58fdcc26c001)
改了好几次，是什么原因呢？奇怪

**Comment by lyc8503** [comment]
抱歉 发现这里确实有个 bug, Terraform 不会应用 worker 的新修改, 我修复下.

**Comment by lyc8503** [comment]
这个问题应该已经解决了, 你可以试试保留配置文件 - 删除项目 - 重建.

**Comment by koala9527** [comment]
已解决
