### ISSUE TITLE
add wechat webhook notification and website authenticaton

### ISSUE THREAD

**Issue by macaty** [lyc8503/UptimeFlare#12]
1、Add customized weibo webhook push
2、add page verification, user name, password authentication

**Comment by macaty** [comment]
3、add the set maintenance window, such as 0-6 , does not affect the availability and does not push alarm notification

**Comment by lyc8503** [comment]
1. 现在企业微信新注册的账号推送需要强制绑定 "可信 IP", 也就要求请求接口的源 IP 固定, Cloudflare Workers 做不到这一点, 想要实现 Wechat 推送就比较麻烦... (比如需要一台中转服务器)

2 和 3 可以作为新 feature 实现

**Comment by lyc8503** [comment]
HTTP 认证已经实现, 请参考配置文件进行配置.

消息推送目前已经通过 apprise 实现几乎所有主流消息推送, 请参考 Wiki.
