### ISSUE TITLE
Q: 是否有私有化部署的方案

### ISSUE THREAD

**Issue by rysinal** [lyc8503/UptimeFlare#14]
需要监控的网站在内网环境，是否可以提供内网环境部署方案

**Comment by lyc8503** [comment]
目前本项目依赖 Cloudflare Workers 平台，这是个云平台，要内网部署的话需要较多修改。本项目的主要特色也就是可以无需自己的服务器，部署多地区的监控服务。

如果你需要 self-host 的话我推荐另一个项目：[uptime-kuma](https://github.com/louislam/uptime-kuma)
