### ISSUE TITLE
部署到CF的时候报错了，能分析下是什么原因吗？

### ISSUE THREAD

**Issue by KyleKwan2024** [lyc8503/UptimeFlare#15]
![image](https://github.com/lyc8503/UptimeFlare/assets/156627560/9ad30ece-e87f-4ff6-96eb-a4892d7cdeb4)

**Comment by lyc8503** [comment]
请复制上面 `Deploy using Terraform` 的完整日志，去除可能的敏感信息后发到此处，应该是 `Deploy using Terraform` 步骤失败了。

**Comment by KyleKwan2024** [comment]
> 请复制上面 `Deploy using Terraform` 的完整日志，去除可能的敏感信息后发到此处，应该是 `Deploy using Terraform` 步骤失败了。

[Deploy using Terraform.txt](https://github.com/lyc8503/UptimeFlare/files/15262981/Deploy.using.Terraform.txt)

**Comment by lyc8503** [comment]
似乎因为某些不明原因，你的部署只成功了一部分，你可以尝试删除 Cloudflare 中所有的资源重新部署尝试下。如果仍然失败，请给出新的 Deploy 步骤中的日志。

检查以下两个 Tab，删除所有和 Uptimeflare 有关的内容：
![image](https://github.com/lyc8503/UptimeFlare/assets/36782264/8cc3d5de-800f-4d71-86a7-664ef187d2c1)


另外，你能找到第一次运行的 `Deploy using Terraform` 步骤时的日志吗？（应该是你设置完 Cloudflare API Key 之后第一次运行 Actions 时的日志）

**Comment by lyc8503** [comment]
有另一个 issue 提出了类似问题，参考这个步骤应该能解决：https://github.com/lyc8503/UptimeFlare/issues/34#issuecomment-2132469300

**Comment by lyc8503** [comment]
因为没有回复，所以暂时关闭了。

最新的版本已经修复了几个部署相关的问题，你可以重新部署尝试一下，如果仍有问题的话可以重新打开 issue 或新开 issue。
