### ISSUE TITLE
建议功能：希望有一个方法能够查看单个目标的状态

### ISSUE THREAD

**Issue by BilikoX** [lyc8503/UptimeFlare#16]
项目非常漂亮，希望有一个方法能够查看单个目标的状态，以方便嵌入到其他网页中
例如: https://xxx.example.com/foo_monitor
![image](https://github.com/lyc8503/UptimeFlare/assets/15882517/64878c92-0c4e-4f1f-853d-68a284abc7d9)

**Comment by lyc8503** [comment]
已经实现, 在 URL 末尾加入 `#id` 即可(当然, 你首先需要更新你自己的仓库, 重新部署新版本.)

例如: https://status.lyc8503.site/#www, 其中 `www` 是配置文件中的 id

![image](https://github.com/lyc8503/UptimeFlare/assets/36782264/76188eab-3351-43ad-adc0-75a579ce6e04)
