### ISSUE TITLE
There were response time data record, but still showed 0%

### ISSUE THREAD

**Issue by joe94540712** [lyc8503/UptimeFlare#17]
Because my website has IP access restriction on specific countries, so I set specific region routing according to [Geo specific checks setup](https://github.com/lyc8503/UptimeFlare/wiki/Geo-specific-checks-setup)

Before creating the specific region, no response time data could be collected, and the percentage was also 0% (this is normal)

However, after the creation of the routing to the specific region was completed, though response time data could be collected, the percentage was still 0%

Any suggestions? Thanks.

![CleanShot 2024-05-10 at 14 34 28@2x](https://github.com/lyc8503/UptimeFlare/assets/41618558/644cb321-11b9-45a2-bd3d-0b71998bbc55)

**Comment by lyc8503** [comment]
You can open this link: https://dash.cloudflare.com/redirect?account=workers/services/view/uptimeflare_worker/production/logs/live

This should redirect you to the `Real time logs` pages of your worker. Click on `Begin log stream` and wait for a minute, you'll see some log entries. Please paste them here.

Also, could you please provide your `uptime.config.ts` with `checkLocationWorkerRoute` in it?

**Comment by joe94540712** [comment]
This is the real-time log information, and the connection URL is the value I filled out in `checkLocationWorkerRoute`.

![CleanShot 2024-05-10 at 14 59 50@2x](https://github.com/lyc8503/UptimeFlare/assets/41618558/f31142dc-9726-4553-a0e5-1158da41fd8e)

In addition, I have filled out the `checkLocationWorkerRoute` info in `uptime.config.ts`.
The only difference is that I filled in `checkLocationWorkerRoute` is `https://` and in the real-time log is `http://`.

**Comment by lyc8503** [comment]
This may be a known issue, please take a look at #7, you have to disable "Always Use HTTPS" and change your worker route protocol to `http://`.

Also, to verify my guess, please expand the `* * * * *` CRON job to see its full log.

**Comment by joe94540712** [comment]
I noticed #7 , I checked specifically, and `Always Use HTTPS` was not enabled for the domain
The logs in` * * * * * `do not mention the `Error calling worker: TypeError: Too many redirects` mentioned in #7 

Do I need to change the `checkLocationWorkerRoute` in `uptime.config.ts` from `https://location.example` to `http://location.example`?

In addition, the log in` * * * * * `is as follows
```
{
  "outcome": "ok",
  "scriptVersion": {
    "id": "aaaaaa-0f00-4296-92e4-bbbbbb"
  },
  "scriptName": "uptimeflare_worker",
  "diagnosticsChannelEvents": [],
  "exceptions": [],
  "logs": [
    {
      "message": [
        "Running scheduled event on DTW..."
      ],
      "level": "log",
      "timestamp": 1715324357042
    },
    {
      "message": [
        "[DTW] Checking ServiceA..."
      ],
      "level": "log",
      "timestamp": 1715324357129
    },
    {
      "message": [
        "Calling worker: https://location.example/"
      ],
      "level": "log",
      "timestamp": 1715324357129
    },
    {
      "message": [
        "[DTW] Checking ServiceB..."
      ],
      "level": "log",
      "timestamp": 1715324357363
    },
    {
      "message": [
        "Calling worker: https://location.example/"
      ],
      "level": "log",
      "timestamp": 1715324357363
    },
    {
      "message": [
        "[DTW] Checking ServiceC..."
      ],
      "level": "log",
      "timestamp": 1715324357596
    },
    {
      "message": [
        "Calling worker: https://location.example/"
      ],
      "level": "log",
      "timestamp": 1715324357596
    },
    {
      "message": [
        "[DTW] Checking Server1..."
      ],
      "level": "log",
      "timestamp": 1715324357824
    },
    {
      "message": [
        "Server1 connected to 123.123.123.123:123"
      ],
      "level": "log",
      "timestamp": 1715324357994
    },
    {
      "message": [
        "[DTW] Checking Server2..."
      ],
      "level": "log",
      "timestamp": 1715324357994
    },
    {
      "message": [
        "Server2 connected to 456.456.456.456:456"
      ],
      "level": "log",
      "timestamp": 1715324358066
    },
    {
      "message": [
        "statusChanged: false, lastUpdate: 1715324177, currentTime: 1715324357"
      ],
      "level": "log",
      "timestamp": 1715324358066
    },
    {
      "message": [
        "Updating state..."
      ],
      "level": "log",
      "timestamp": 1715324358066
    }
  ],
  "eventTimestamp": 1715324357038,
  "event": {
    "cron": "* * * * *",
    "scheduledTime": 1715324357000
  },
  "id": 7
}
```

**Comment by lyc8503** [comment]
Sorry, then it looks like it's not the same issue. If this is the case, changing `https://` to `http://` may not solve your problem.

Now that it does look like the worker performing the check can't connect to your servers Service A B and C (so they actually reported the “correct” result - DOWN), can you provide a log from the `POST` request?

Also, could you provide a full configuration (e.g. for your `ServiceA`), with sensitive information removed, and post it here.

**Comment by joe94540712** [comment]
The log in `POST` is as follows.
```
{
  "outcome": "ok",
  "scriptVersion": {
    "id": "baaaaaa-0f00-4296-92e4-bbbbbb"
  },
  "scriptName": "uptimeflare_worker",
  "diagnosticsChannelEvents": [],
  "exceptions": [],
  "logs": [
    {
      "message": [
        "Handling request event at TPE..."
      ],
      "level": "log",
      "timestamp": 1715324357733
    },
    {
      "message": [
        "ServiceB responded with 403"
      ],
      "level": "log",
      "timestamp": 1715324357738
    }
  ],
  "eventTimestamp": 1715324357733,
  "event": {
    "request": {
      "url": "http://location.example/",
      "method": "POST",
      "headers": {
        "accept-encoding": "gzip",
        "cf-connecting-ip": "172.68.204.164",
        "cf-ipcountry": "US",
        "cf-ray": "88180bb3c9f9a9c2",
        "cf-visitor": "{\"scheme\":\"http\"}",
        "connection": "Keep-Alive",
        "content-length": "21",
        "content-type": "text/plain;charset=UTF-8",
        "host": "location.example",
        "x-forwarded-for": "2a06:98c0:3600::103",
        "x-forwarded-proto": "http",
        "x-real-ip": "172.68.204.164"
      },
      "cf": {
        "clientTcpRtt": 206,
        "longitude": "-83.04150",
        "httpProtocol": "HTTP/1.1",
        "tlsCipher": "",
        "continent": "NA",
        "asn": 13335,
        "clientAcceptEncoding": "gzip",
        "country": "US",
        "tlsClientExtensionsSha1": "",
        "verifiedBotCategory": "",
        "tlsClientAuth": {
          "certIssuerDNLegacy": "",
          "certIssuerSKI": "",
          "certSubjectDNRFC2253": "",
          "certSubjectDNLegacy": "",
          "certFingerprintSHA256": "",
          "certNotBefore": "",
          "certSKI": "",
          "certSerial": "",
          "certIssuerDN": "",
          "certVerified": "NONE",
          "certNotAfter": "",
          "certSubjectDN": "",
          "certPresented": "0",
          "certRevoked": "0",
          "certIssuerSerial": "",
          "certIssuerDNRFC2253": "",
          "certFingerprintSHA1": ""
        },
        "tlsVersion": "",
        "city": "Detroit",
        "timezone": "America/Detroit",
        "colo": "TPE",
        "tlsClientHelloLength": "",
        "edgeRequestKeepAliveStatus": 1,
        "postalCode": "48272",
        "region": "Michigan",
        "latitude": "42.32550",
        "requestPriority": "",
        "regionCode": "MI",
        "asOrganization": "Cloudflare",
        "metroCode": "505",
        "tlsClientRandom": ""
      }
    },
    "response": {
      "status": 200
    }
  },
  "id": 6
}
```

It seems that even if the connection to a specific region is set, the region that is finally connected to `ServiceA` is the United States. (I also saw the connection log from `ServiceA`'s firewall, so it was blocked.)

In addition, the settings for `ServiceA` in `uptime.config.ts` are as follows.
```
// Example HTTP Monitor
    {
      // `id` should be unique, history will be kept if the `id` remains constant
      id: 'ServiceA',
      // `name` is used at status page and callback message
      name: 'ServiceA',
      // `method` should be a valid HTTP Method
      method: 'POST',
      // `target` is a valid URL
      target: 'https://ServiceA-URL/',
      // [OPTIONAL] `tooltip` is ONLY used at status page to show a tooltip
      tooltip: 'My serviceA',
      // [OPTIONAL] `statusPageLink` is ONLY used for clickable link at status page
      statusPageLink: 'https://ServiceA-URL/',
      // [OPTIONAL] `expectedCodes` is an array of acceptable HTTP response codes, if not specified, default to 2xx
      expectedCodes: [200],
      // [OPTIONAL] `timeout` in millisecond, if not specified, default to 10000
      timeout: 10000,
      // [OPTIONAL] headers to be sent
      headers: {
        'User-Agent': 'Uptimeflare',
        //Authorization: 'Bearer YOUR_TOKEN_HERE',
      },
      // [OPTIONAL] body to be sent
      body: 'Hello, world!',
      // [OPTIONAL] if specified, the response must contains the keyword to be considered as operational.
      responseKeyword: 'success',
      // [OPTIONAL] if specified, the check will run in your specified region,
      // refer to docs https://github.com/lyc8503/UptimeFlare/wiki/Geo-specific-checks-setup before setting this value
      checkLocationWorkerRoute: 'https://location.example/',
    },
```

**Comment by lyc8503** [comment]
According to the logs, the worker actually running the check is TPE (Taipei), not US, which shouldn't cause problems.

What is the source IP of the request you are getting on the server side? How is your server filtering the requests (by headers or by source IP)?

**Comment by joe94540712** [comment]
Because I saw from the server-side logs that the blocked source is the United States, I thought that the specified regional routing was not successful.
In addition, the server filters requests through country IP address (service provided by Cloudflare.)

The records received on my server-side are as follows:
![CleanShot 2024-05-10 at 17 27 39@2x](https://github.com/lyc8503/UptimeFlare/assets/41618558/1f85e2e5-12cc-4491-a774-0a18c26d9ebd)

**Comment by lyc8503** [comment]
I see. The request from the worker is routed inside the Cloudflare network, and at that point Cloudflare still knows where the request is really coming from (US in your case), so if you use Cloudflare's firewall rules, then the firewall rules will block the request. (If the request leaves Cloudflare's network, you'll only see the ip address from the TPE on your origin server's side.)

You may need to solve your problem in a different way: you can modify your firewall rules to detect a unique token header, so that requests are not blocked when they contain the correct token header. You can then add this token to uptime.config.ts so that your monitoring requests are not blocked.

For example, you can update your firewall rule like below:
![image](https://github.com/lyc8503/UptimeFlare/assets/36782264/00d5ebe0-6421-48f6-b4db-2c88c432ab9d)

Then update your `uptime.config.ts` headers like this:
```
headers: {
  'User-Agent': 'Uptimeflare',
  'token': 'A random secret token XXXX'
},
```

**Comment by joe94540712** [comment]
I didn't know about this feature in the routing within Cloudflare network, very interesting.
This reminds me that when using Cloudflare's WARP service, if the target host is also within the Cloudflare network, then that host can obtain the real IP information of the user. However, if the target host is not within the Cloudflare network, then the target host can only obtain Cloudflare's IP connection information. 

I have set up related headers in `uptime.config.ts`, and also disabled `checkLocationWorkerRoute` to observe.
Therefore, my `uptime.config.ts` will become: 
```
// Example HTTP Monitor
    {
      // `id` should be unique, history will be kept if the `id` remains constant
      id: 'ServiceA',
      // `name` is used at status page and callback message
      name: 'ServiceA',
      // `method` should be a valid HTTP Method
      method: 'POST',
      // `target` is a valid URL
      target: 'https://ServiceA-URL/',
      // [OPTIONAL] `tooltip` is ONLY used at status page to show a tooltip
      tooltip: 'ServiceA',
      // [OPTIONAL] `statusPageLink` is ONLY used for clickable link at status page
      statusPageLink: 'https://ServiceA-URL/',
      // [OPTIONAL] `expectedCodes` is an array of acceptable HTTP response codes, if not specified, default to 2xx
      expectedCodes: [200],
      // [OPTIONAL] `timeout` in millisecond, if not specified, default to 10000
      timeout: 10000,
      // [OPTIONAL] headers to be sent
      headers: {
        'User-Agent': 'Uptimeflare',
        'token': 'RANDOM-CODE-INCLUDING-LETTERS-NUMBERS-SYMBOLS',
        //Authorization: 'Bearer YOUR_TOKEN_HERE',
      },
      // [OPTIONAL] body to be sent
      body: 'Hello, world!',
      // [OPTIONAL] if specified, the response must contains the keyword to be considered as operational.
      responseKeyword: 'success',
      // [OPTIONAL] if specified, the check will run in your specified region,
      // refer to docs https://github.com/lyc8503/UptimeFlare/wiki/Geo-specific-checks-setup before setting this value
      //checkLocationWorkerRoute: 'https://location.example/',
    },
```
Of course, I also set up the header rules in Cloudflare's firewall.
![CleanShot 2024-05-11 at 00 59 29](https://github.com/lyc8503/UptimeFlare/assets/41618558/70b48c81-2833-4e98-94a4-4601b2347b64)


However, even after the adjustments above, the status page still shows DOWN.
I checked the `uptimeflare_work` and server logs again, and found that after adjustment, the server's firewall did not have any block records. However, the logs of `uptimeflare_work` are a bit strange, the response from `ServiceA` is 200, while the response from `ServiceB` and `ServiceC` is 405. And even though `ServiceA` responds with 200, it still shows as DOWN on the status page.

```
{
  "outcome": "ok",
  "scriptVersion": {
    "id": "1aaaa-5eab-4a97-81c8-ebbbbb"
  },
  "scriptName": "uptimeflare_worker",
  "diagnosticsChannelEvents": [],
  "exceptions": [],
  "logs": [
    {
      "message": [
        "Running scheduled event on TPE..."
      ],
      "level": "log",
      "timestamp": 1715359749157
    },
    {
      "message": [
        "[TPE] Checking ServiceA..."
      ],
      "level": "log",
      "timestamp": 1715359749463
    },
    {
      "message": [
        "ServiceA responded with 200"
      ],
      "level": "log",
      "timestamp": 1715359749497
    },
    {
      "message": [
        "[TPE] Checking ServiceB..."
      ],
      "level": "log",
      "timestamp": 1715359749497
    },
    {
      "message": [
        "ServiceB responded with 405"
      ],
      "level": "log",
      "timestamp": 1715359749527
    },
    {
      "message": [
        "[TPE] Checking ServiceC..."
      ],
      "level": "log",
      "timestamp": 1715359749527
    },
    {
      "message": [
        "ServiceC responded with 405"
      ],
      "level": "log",
      "timestamp": 1715359749557
    },
    {
      "message": [
        "[TPE] Checking TCP1..."
      ],
      "level": "log",
      "timestamp": 1715359749557
    },
    {
      "message": [
        "TCP1 connected to 123.123.123.123:123"
      ],
      "level": "log",
      "timestamp": 1715359749643
    },
    {
      "message": [
        "[TPE] Checking TCP2..."
      ],
      "level": "log",
      "timestamp": 1715359749643
    },
    {
      "message": [
        "TCP2 connected to 456.456.456.456:456"
      ],
      "level": "log",
      "timestamp": 1715359749824
    },
    {
      "message": [
        "statusChanged: false, lastUpdate: 1715359630, currentTime: 1715359749"
      ],
      "level": "log",
      "timestamp": 1715359749824
    },
    {
      "message": [
        "Skipping state update due to cooldown period."
      ],
      "level": "log",
      "timestamp": 1715359749824
    }
  ],
  "eventTimestamp": 1715359749141,
  "event": {
    "cron": "* * * * *",
    "scheduledTime": 1715359749000
  },
  "id": 2
}
```
![CleanShot 2024-05-11 at 00 56 44](https://github.com/lyc8503/UptimeFlare/assets/41618558/d92f75a0-b5bd-496d-822c-5ee3f43fe7c3)

**Comment by lyc8503** [comment]
HTTP Code `405` stands for `Method Not Allowed`, there is a high probability that this response code means that you have configured the wrong `method`.

You used `POST` for ServiceA, what method did you configure for ServiceB and C? Is the server able to respond to this method? you may want to look at the logs on your origin server. You probably want `GET` if it's just a simple web page.

As for ServiceA, you keep the `responseKeyword: 'success'` in the configuration file, which means that the server's response must contain the success string to be considered operational. Your server probably doesn't include the "success" string in the response, so you can just comment out the `responseKeyword` entry.

You did give me a heads up though, I could probably print the reason for the failure in the log to make debugging easier😂 I'll add it in a later update.

**Comment by lyc8503** [comment]
In fact, most of the items in the full configuration are not needed for simple webpage monitoring, and I'll update the documentation with some simple samples for reference, rather than just giving the full configuration file in too much detail.

**Comment by joe94540712** [comment]
Thank you, you pointed out the key point.
I did indeed overlook the role of `responseKeyword: 'success'`, and after commenting it out, `ServiceA` also functioned normally.
Regarding `ServiceB` and `ServiceC`, I originally used `POST` as well, but found that these two webpages did not support it, so after switching to `GET`, they also functioned normally. (A reminder for those encountering the same issue: if switching from `POST` to `GET`, remember to remove the `body` section as well).

Thank you again for your time and assistance.

**Comment by joe94540712** [comment]
> You did give me a heads up though, I could probably print the reason for the failure in the log to make debugging easier😂 I'll add it in a later update.

Agree and support, and if this part could also be printed out, it would indeed be very helpful for debugging. 👍
