### ISSUE TITLE
How to Check telnet port 1688

### ISSUE THREAD

**Issue by iougemini** [lyc8503/UptimeFlare#18]
How can I detect the 1688 port of the server, as TCP-ping is not working properly currently.
But, using [uptime-kuma](https://github.com/louislam/uptime-kuma) TCP Port feature can normally check.

**Comment by lyc8503** [comment]
Hi, theoretically this program supports monitoring telnet ports using TCP Ping, I need more information to help you.

Could you please provide me the part of your configuration file that is relevant to this Telnet monitoring.

Also, could you please visit the link https://dash.cloudflare.com/redirect?account=workers/services/view/uptimeflare_worker/production/logs/live and click on `Begin log stream` and wait for a while, you will see some log entries, please send the full captured logs here.

**Comment by lyc8503** [comment]
It's closed for now because it's inactive. If the problem persists, please add the required information and re-open the issue.
