### ISSUE TITLE
部署之后异常

### ISSUE THREAD

**Issue by pengchangg** [lyc8503/UptimeFlare#2]
部署地址： https://uptimeflare-ese.pages.dev/
![image](https://github.com/lyc8503/UptimeFlare/assets/55234547/a75ca11a-dc70-4e87-9b24-9c2b99e1f377)
![image](https://github.com/lyc8503/UptimeFlare/assets/55234547/7231f90b-a0fd-4da9-8df3-6bf6621f4c0c)

**Comment by lyc8503** [comment]
看情况是 Worker 没有正确运行，检查一下第一次 GitHub Actions 部署过程中是否出现错误，再看下 Cloudflare Dashboard 中 Worker 是否有运行记录。

**Comment by pengchangg** [comment]
我是使用 `Use this template`  自动触发了 `Actions` 还没有设置`Key` 第一次是必然失败的，我现在把Cloudflare中的相关资源都删除了，重新运行了第一次 `Acitons` （页面正常工作了，但是由于第一次是自动触发的，所有配置是错误的 导致目前的数据是有问题的），然后把我修改配置之后的`Acitons`重新运行了一次。 目前看起来页面恢复了正常。

**Comment by lyc8503** [comment]
> 我是使用 `Use this template` 自动触发了 `Actions` 还没有设置`Key` 第一次是必然失败的，我现在把Cloudflare中的相关资源都删除了，重新运行了第一次 `Acitons` （页面正常工作了，但是由于第一次是自动触发的，所有配置是错误的 导致目前的数据是有问题的），然后把我修改配置之后的`Acitons`重新运行了一次。 目前看起来页面恢复了正常。

抱歉没说清楚，我指的第一次运行就是指你刚设置完 TOKEN 后的第一次运行，应该会使用 Terraform 部署相关资源。

理论上没有设置 TOKEN 就运行 Actions 什么都不会做，所以 `Use this template` 触发的 Actions 不应该导致部署出现问题。

**Comment by pengchangg** [comment]
确实 设置token之后 部署的时候我把配置里面的 邮箱配置注释了  然后他就报错了，后续修改之后重新跑Actions才通过的
![image](https://github.com/lyc8503/UptimeFlare/assets/55234547/ca11940b-cc68-48d8-bf36-6071d51f9575)

**Comment by lyc8503** [comment]
OK, 这里应该是我写的不太严谨导致编译错误, 我稍后修改下.

**Comment by pengchangg** [comment]
> OK, 这里应该是我写的不太严谨导致编译错误, 我稍后修改下.

谢谢~总之成功解决。感觉这个项目很不错呀，其他的类似项目感觉都太重了，

**Comment by lyc8503** [comment]
110a6b5 中修复了, 目前可以不设置 `highlight`
