### ISSUE TITLE
status page看到的数据，是cloudflare多个位置的平均数据还是用户访问到的边缘点探测到数据

### ISSUE THREAD

**Issue by LHB6540** [lyc8503/UptimeFlare#20]
请教下，status page看到的数据，是cloudflare多个位置的平均数据还是用户访问到的边缘点探测到数据。如果是前者，数据是如何汇总和存储的？

**Comment by lyc8503** [comment]
用于监测服务状态的 Worker 是由配置的 CRON 触发的, 触发后, 此 Worker 将在 Cloudflare 的调度下, 在当前负载较低的一个边缘运行监测.

所以你看到的数据既不是平均, 也不是当前用户访问到的边缘服务器, 而是一个比较"随机"的边缘服务器, 取决于 Cloudflare 的内部调度策略. 鼠标移到延迟图上可以看到某次监测对应的边缘服务器.
![image](https://github.com/lyc8503/UptimeFlare/assets/36782264/957a2e6f-5be3-408b-8229-0d9d7753b2f5)

如果你要指定从某个固定的地区访问服务器, 请参考 Wiki 配置 `checkLocationWorkerRoute` 项目.

目前没有实现从多个位置同时监测同一网站的功能, 当然技术上是可以通过支持指定多个 `checkLocationWorkerRoute` 实现, 不过这样就有些逻辑需要修改, 而且目前 Cloudflare 平台 Worker 的并发数目限制比较严格, 顺序监测可能导致每次监测耗时较长, 所以暂未实现.

**Comment by LHB6540** [comment]
好的，了解了，谢谢
