### ISSUE TITLE
How should I update my branch after the upstream code is updated?

### ISSUE THREAD

**Issue by p0we7** [lyc8503/UptimeFlare#21]

**Comment by lyc8503** [comment]
There are two approaches.
1. Use Git on your computer to pull my repository (upstream) and merge it into your own. Refer to: https://stackoverflow.com/questions/56577184/github-pull-changes-from-a-template-repository
2. Backup your current `uptime.config.ts`, delete your current repository, recreate the repository from the template, set the environment variables, restore the config file and you're done!

Just choose the one you find more convenient :)

**Comment by lyc8503** [comment]
Added in [Wiki](https://github.com/lyc8503/UptimeFlare/wiki), thanks for your advice!
