### ISSUE TITLE
部署的监控，为什么全部超时

### ISSUE THREAD

**Issue by 196180** [lyc8503/UptimeFlare#23]
![IMG_20240515_112232](https://github.com/lyc8503/UptimeFlare/assets/152402505/78497040-e6ad-432d-9cbe-ee5959499448)

楼主请解答一下

**Comment by lyc8503** [comment]
您好，请给出你的完整的 `uptime.config.ts` 文件，注意移除其中的敏感信息。

你是否照抄了 Wiki 中的参考配置，其中很多配置项目对于普通的监控是不需要的？

**Comment by 0x5c0f** [comment]
> 您好，请给出你的完整的 `uptime.config.ts` 文件，注意移除其中的敏感信息。
> 
> 你是否照抄了 Wiki 中的参考配置，其中很多配置项目对于普通的监控是不需要的？

同问这个问题，我的 `uptime.config.ts`中，我只修改了`workerConfig.monitors` 的内容，且只保留了`id`、`name`、`method`、`target` 、`tooltip`、`statusPageLink`、`expectedCodes`、`timeout`、`headers`、`body` , 其他项删除

**Comment by 0x5c0f** [comment]
> > 您好，请给出你的完整的 `uptime.config.ts` 文件，注意移除其中的敏感信息。
> > 你是否照抄了 Wiki 中的参考配置，其中很多配置项目对于普通的监控是不需要的？
> 
> 同问这个问题，我的 `uptime.config.ts`中，我只修改了`workerConfig.monitors` 的内容，且只保留了`id`、`name`、`method`、`target` 、`tooltip`、`statusPageLink`、`expectedCodes`、`timeout`、`headers`、`body` , 其他项删除

我的问题已经解决，我的`method`指定为`GET`，而我却又配置`body`，我将`body`删除后，监控正常

**Comment by 196180** [comment]
感谢，我的问题已经解决

**Comment by lyc8503** [comment]
似乎有不少人遇到了配置文件相关的问题，我之后会完善一下文档，提供更加简洁的配置文件作为示例，感谢你们提出的问题。
