### ISSUE TITLE
Feature Request: Custom Notifications

### ISSUE THREAD

**Issue by Its4Nik** [lyc8503/UptimeFlare#25]
In the docker container version (I'm working on it rn), I would love to add a volume where you can mount custom “scripts” which then can be used as notification service.

What I am achieving with this? 
Well more notifications and some customization options. My main goal is to make ntfy, discord and that stuff available as notification service. Well anything to be honest would be supported by that.

My Idea for mounting those files would be in `/app/custom_notifications/`. I know this ain't an option for Cloudflare workers. But I strongly believe this is a viable option because a lot of people would rather run a docker container then a Cloudflare Worker (just my opinion).

So now my question is would this be a good idea @lyc8503?

**Comment by Its4Nik** [comment]
And maybe for the docker container a simpler YAML configuration option. Which will just be parsed into the right .ts config

**Comment by lyc8503** [comment]
I don't really want to introduce a lot of dynamic imports into the project and maintain a special interface for custom notifications “plugins”.

There are [so many optional pushes](https://github.com/louislam/uptime-kuma/tree/master/src/components/notifications) now that maintaining them is a chore.

For now, the way to customize push is to write your own code in `uptime.config.ts` and use `fetch` to access the corresponding API, I know this approach is unfriendly to people who don't know Javascript programming, so it might be a good idea to introduce a library dedicated to implementing various pushes, e.g. https://github.com/caronc/apprise

But for the time being, I'm not going to maintain all the push services in the repository (at most, I'll only support some of the major pushes), and I'm not going to maintain the custom script functionality that you're talking about for pushes.

**Comment by lyc8503** [comment]
> And maybe for the docker container a simpler YAML configuration option. Which will just be parsed into the right .ts config

The current configuration file does seem a bit cumbersome, I'll refine the documentation a bit afterward to provide more examples and instructions.

**Comment by Its4Nik** [comment]
> > And maybe for the docker container a simpler YAML configuration option. Which will just be parsed into the right .ts config
> 
> The current configuration file does seem a bit cumbersome, I'll refine the documentation a bit afterward to provide more examples and instructions.

that would be awesom, i find myself pretty lost here and there!

> I don't really want to introduce a lot of dynamic imports into the project and maintain a special interface for custom notifications “plugins”.
> 
> There are [so many optional pushes](https://github.com/louislam/uptime-kuma/tree/master/src/components/notifications) now that maintaining them is a chore.
> 
> For now, the way to customize push is to write your own code in `uptime.config.ts` and use `fetch` to access the corresponding API, I know this approach is unfriendly to people who don't know Javascript programming, so it might be a good idea to introduce a library dedicated to implementing various pushes, e.g. https://github.com/caronc/apprise
> 
> But for the time being, I'm not going to maintain all the push services in the repository (at most, I'll only support some of the major pushes), and I'm not going to maintain the custom script functionality that you're talking about for pushes.

Yeah I totally get that, and if the documentation gets better and also the community support then it would be a really good viable option. 

Thanks for sharing your thought process, cool to learn how people think! :)
