### ISSUE TITLE
[Feature Request]   监控目标希望可以指定解析地址 

### ISSUE THREAD

**Issue by 0x5c0f** [lyc8503/UptimeFlare#26]
# 需求 
如果可以，希望能在进行 `HTTP Monitor` 的时候可以为监控目标指定解析的地址 ，关于这个我似乎并未在现有配置项中找到这个问题的解决方案

# 应用场景
我现在有这么一个应用场景，我的静态博客站点，分别部署在`阿里云`和`vercel`, 然后通过`dns`解析区分不同区域流量。根据部署的`UptimeFlare`请求来看，他的流量来自美国，这个时候这个的请求只会到`vercel`的站点上面。如果能指定解析地址，就可以解决这个问题，或者是否有其他方案解决这个问题呢。

**Comment by lyc8503** [comment]
目前是支持[指定地区监控](https://github.com/lyc8503/UptimeFlare/wiki/Geo-specific-checks-setup)的，但是 Cloudflare 没有中国大陆的边缘节点，这可能不能解决你的问题。

由于 Cloudflare 平台的限制，只能为自己拥有的、NS 接入了 Cloudflare 的域名 override DNS 解析的结果，考虑到 Cloudflare 不支持分地区解析的功能，（我猜测）你使用的应该是阿里云的 DNS，所以你的需求在 Cloudflare Workers 上是不能实现的。

目前的情况下，你可以在你的 DNS 管理中手动创建两个域名，例如 `_aliyun._internal.yoursite.com` 和 `_vercel._internal.yoursite.com`，分别 CNAME 指向阿里云和 Vercel，然后对两个域名分别设立监控。

偷懒的话，你也可以直接对你的 OSS Bucket （`https://xxx.oss-cn-shanghai.aliyuncs.com/`）进行监控，作为国内的监控。

这应该能解决你的问题。

**Comment by 0x5c0f** [comment]
> 目前是支持[指定地区监控](https://github.com/lyc8503/UptimeFlare/wiki/Geo-specific-checks-setup)的，但是 Cloudflare 没有中国大陆的边缘节点，这可能不能解决你的问题。
> 
> 由于 Cloudflare 平台的限制，只能为自己拥有的、NS 接入了 Cloudflare 的域名 override DNS 解析的结果，考虑到 Cloudflare 不支持分地区解析的功能，（我猜测）你使用的应该是阿里云的 DNS，所以你的需求在 Cloudflare Workers 上是不能实现的。
> 
> 目前的情况下，你可以在你的 DNS 管理中手动创建两个域名，例如 `_aliyun._internal.yoursite.com` 和 `_vercel._internal.yoursite.com`，分别 CNAME 指向阿里云和 Vercel，然后对两个域名分别设立监控。
> 
> 偷懒的话，你也可以直接对你的 OSS Bucket （`https://xxx.oss-cn-shanghai.aliyuncs.com/`）进行监控，作为国内的监控。
> 
> 这应该能解决你的问题。

我明白了，我的确可以通过创建两个别名，用来分别指向`阿里云`和`vercel`上的站点，然后监控这两个地址，来达到我的目的。只是我的本意是想，我可以直接通过`uptime.config.ts` 配置文件来直接绑定我的域名目标，就像主机上本地的`hosts`绑定那样

**Comment by lyc8503** [comment]
我明白你的意思，但你想实现的功能在 Cloudflare Workers 上是不可能的：因为 Cloudflare Workers 只提供了 `fetch` 接口，提供的 [`resolveOverride`](https://developers.cloudflare.com/workers/runtime-apis/request/#the-cf-property-requestinitcfproperties) 选项要求访问的目标服务器绑定在你的 Cloudflare 下才行。

~~不过 vercel/Cloudflare 本身国内访问速度也可以接受，直接统一访问 vercel，不用阿里云也是可以的。~~
