### ISSUE TITLE
新功能建议

### ISSUE THREAD

**Issue by littleyz** [lyc8503/UptimeFlare#27]
非常感谢开发如此功能的服务。提2个新功能建议：
1. 建议增加分组功能。
2. 另外每个监控能单独设置 DetailBar和DetailChart的显示与否。

**Comment by lyc8503** [comment]
1. 具体分组功能是想要怎样实现呢？
2. 如果 Bar 和 Chart 都不显示的话，那就只有当前状态(Up/Down) + Percent 的数字了，是不是看起来有点少

**Comment by littleyz** [comment]
可以在uptime.config.ts配置文件里加上配置选项，比如分组功能，
group : 服务器监控

（这样前端监控页面会按照分组显示
服务器监控
    服务器一
    服务器二

服务监控
   监控点一
   监控点二）


至于是否显示bar和chart：
bar display: on/off
chart display: on/off

以上用户可以自己配置。

**Comment by lyc8503** [comment]
#38 中描述的比较详细，而且是英文的（更方便国际友人查询），所以暂时关闭此 issue，之后的讨论可以合并进 #38
