### ISSUE TITLE
http服务检测非标准端口异常

### ISSUE THREAD

**Issue by pengchangg** [lyc8503/UptimeFlare#3]
## http服务检测非标准端口异常，我不知道是否支持端口的配置，如果有请告诉我怎么配置，我在配置文件中没有看到配置项
![image](https://github.com/lyc8503/UptimeFlare/assets/55234547/ec857238-8783-4fed-93cf-8e82445ac453)
![image](https://github.com/lyc8503/UptimeFlare/assets/55234547/43f355c7-5c11-41e2-bf98-9b9801210248)
![image](https://github.com/lyc8503/UptimeFlare/assets/55234547/2adc5a81-c19c-4d6a-af7d-f5f5cb0d7d76)

## tcp 自定义端口是正常的
![image](https://github.com/lyc8503/UptimeFlare/assets/55234547/419b8eec-36ab-4ce6-a419-d5ce431c645f)
![image](https://github.com/lyc8503/UptimeFlare/assets/55234547/08de719f-56d0-4c13-98fe-02632f8603ac)

**Comment by lyc8503** [comment]
证书是否正常? 目前可能还不支持自签的证书...

**Comment by lyc8503** [comment]
目前使用的 fetch API 没有提供不检验 https 证书的功能, 可能需要一些其他的 workaround...

https://community.cloudflare.com/t/fetch-self-signed-websites/443117/2

**Comment by pengchangg** [comment]
好吧，我大概知道了，目前还发现了一个问题。我有问题的的检测项的配置注释之后，监控的数据面板并不会将此项的历史检测数据清除。

**Comment by lyc8503** [comment]
> 好吧，我大概知道了，目前还发现了一个问题。我有问题的的检测项的配置注释之后，监控的数据面板并不会将此项的历史检测数据清除。

历史记录是和 ID 绑定的, 你更换一个不同的 ID 就会清空记录了.

监测非 443 端口的 https 是可以的, 但暂时不支持自签, 可以配置下 Let's Encrypt 的证书.

**Comment by lyc8503** [comment]
非标端口的检测已经在最新版本修复（不过目前还是需要非自签的 SSL 证书）
