### ISSUE TITLE
HTTP GET 方式没有响应

### ISSUE THREAD

**Issue by yankeeshcn** [lyc8503/UptimeFlare#31]
你好，lyc8503：我按照你的例子来配置uptimeconfig文件，但是一直没有解决http get网站请求的失败的问题。
配置如下，请给予帮助。谢谢！
![1](https://github.com/lyc8503/UptimeFlare/assets/45564413/e73d9047-b2ef-4dfb-947f-6328d4778a73)

 monitors: [
    // Example HTTP Monitor
    {
      // `id` should be unique, history will be kept if the `id` remains constant
      id: 'foo_monitor',
      // `name` is used at status page and callback message
      name: 'My API Monitor',
      method: 'GET',
      target: 'http://www.resmtech.com/',
      tooltip: 'This is a tooltip for this monitor',
      statusPageLink: 'http://www.resmtech.com/',
      expectedCodes: [200],
      timeout: 10000,
      headers: {
        'User-Agent': 'Uptimeflare',
        Authorization: 'e861ff9e-8c97-4b12-b9c2-8bef3b27ff0d',
      },
      checkLocationWorkerRoute: 'http://jp.yankeey.top/',
    },

**Comment by lyc8503** [comment]
您好，我看到你 `http://jp.yankeey.top/` 打开显示的是 Error 1000 DNS points to prohibited IP

这可能表示你根据 Wiki 选择的区域 Worker IP 不能使用，你可能需要换一个 IP，你也可以先尝试不指定 checkLocationWorkerRoute，看看不指定时能不能正确检测。

checkLocationWorkerRoute 不是必须的，只在某些连接性较差的情况下需要使用。

**Comment by yankeeshcn** [comment]
感谢回复，我试试看。

**Comment by lyc8503** [comment]
因为没有回复暂时关闭了，如果问题仍然存在的话可以 reopen。
