### ISSUE TITLE
IPv6 support for workers

### ISSUE THREAD

**Issue by lohrbini** [lyc8503/UptimeFlare#33]
Hey there 👋,

since most of my sites are only reachable via IPv6 I wanted to ask how to add this to the app. When adding tcp checks on IPv6 addresses the services are always shown as down

**Comment by lyc8503** [comment]
Hello, IPv6 checking is now supported (there're IPv6-only sites on https://status.lyc8503.site), can you describe the problem more specifically and provide your configuration file after removing the sensitive information?

**Comment by lohrbini** [comment]
I am not sure how to debug them. If i configure a monitor like this

```
..
    {
      id: 'v6_tcp_https',
      name: 'pub v6 tcp',
      method: 'TCP_PING',
      target: '[IPv6_Address_here]:443',
      tooltip: 'v4proxy SSL tcp check',
      statusPageLink: 'https://uptime.skl.works',
    },
..
```

The check should work. Or is it a problem with an non matching ssl certificate ? I guess not since its tcp not http

**Comment by lyc8503** [comment]
You can capture your worker's logs on this page: https://dash.cloudflare.com/redirect?account=workers/services/view/uptimeflare_worker/production/logs/live

However, judging from the https://uptime.skl.works/ page, the reason for the error is a connection timeout, which means that Cloudflare Workers didn't complete the TCP handshake with your server within 10s.

For example, if I want to check the SSH port (22) of the “2001:bc8:1d80:2140::1” server, I would write this configuration:
```typescript
{
  id: "my_ssh",
  name: "My Server SSH",
  method: "TCP_PING",
  target: "[2001:bc8:1d80:2140::1]:22"
}
```

If it's not a configuration file issue, you can check online if your server port is indeed open using the ping.pe site, like this: https://tcp6.ping.pe/[2001:bc8:1d80:2140::1]:22.

**Comment by lohrbini** [comment]
I´ve installed wrangler yesterday to look at the looks and see multiple issues with wrong http codes. I guess I need to take a look at the worker location first before adding more monitors.

Thanks! Ticket will be closed
