### ISSUE TITLE
The program reported an error after deleting the `statusPageLink`

### ISSUE THREAD

**Issue by aoaim** [lyc8503/UptimeFlare#39]
Recently, it was found that after deleting `statusPageLink: 'https://example.com'` during deployment, the program reported an error. It seems that this is a required field. Can this field be removed? I don't quite understand the purpose of `statusPageLink`. It seems useful for monitoring web but not for `tcp_ping`. 

In addition to web and `tcp_ping`, are there other monitoring methods supported? Does it support notification channels like bark?

**Comment by lyc8503** [comment]
> Can this field be removed?

removing `statusPageLink` should not affect deployment, I configured it this way myself, can you give specific error messages?

> I don't quite understand the purpose of statusPageLink.

the purpose of `statusPageLink` is to make the title on the frontend page a clickable hyperlink, which has nothing to do with the actual monitoring, so TCP_PING can also specify a link.

> In addition to web and tcp_ping, are there other monitoring methods supported?

Is there anything else you would like to implement for monitoring?

> Does it support notification channels like bark?

The current notification provider (apprise) supports Bark, please refer to the Wiki.

**Comment by lyc8503** [comment]
A detailed issue with `statusPageLink` was raised in #41 and resolved in #43.
