### ISSUE TITLE
Run-Again

### ISSUE THREAD

**Issue by s7net** [lyc8503/UptimeFlare#4]
It doesn't run again in GitHub Action

https://status.tala.network

**Comment by lyc8503** [comment]
Please check your GitHub Actions status and see if there're any error messages. If you made a mistake in your configuration, the redeployment would fail.

**Comment by s7net** [comment]
![image](https://github.com/lyc8503/UptimeFlare/assets/148908703/b6576fe3-13de-4aaf-9e36-a8f44b71ea1c)

**Comment by lyc8503** [comment]
Then please attach the full log for this job for debugging.

**Comment by s7net** [comment]
https://pipelinesghubeus15.actions.githubusercontent.com/0wbYbddhnmSImiNRLprMrrlr05dEssYujsKWRk7lVKaJtUEJYx/_apis/pipelines/1/runs/40/signedlogcontent/2?urlExpires=2024-01-06T09%3A58%3A03.4297458Z&urlSigningMethod=HMACV1&urlSignature=FNU1kkyK7RweTacJ2VTlsSLwYyyKt7g1tLmP6NIfhTI%3D

**Comment by s7net** [comment]
wait

**Comment by lyc8503** [comment]
> https://pipelinesghubeus15.actions.githubusercontent.com/0wbYbddhnmSImiNRLprMrrlr05dEssYujsKWRk7lVKaJtUEJYx/_apis/pipelines/1/runs/40/signedlogcontent/2?urlExpires=2024-01-06T09%3A58%3A03.4297458Z&urlSigningMethod=HMACV1&urlSignature=FNU1kkyK7RweTacJ2VTlsSLwYyyKt7g1tLmP6NIfhTI%3D

I can't see this. It says:
```
{
  count: 11
  value: "Uri expired"
}
```

Please attach a screenshot or copy-paste your log with a code block.

**Comment by s7net** [comment]
[GitLog.txt](https://github.com/lyc8503/UptimeFlare/files/13849083/GitLog.txt)

**Comment by s7net** [comment]
see this

**Comment by lyc8503** [comment]
It seems that your worker is deployed correctly but something is wrong when it's running.

Please take a look at your worker's running status at Cloudflare Dashboard.

**Comment by s7net** [comment]
![image](https://github.com/lyc8503/UptimeFlare/assets/148908703/5c4522a5-dffb-4b1d-a857-a47c2168bbfd)

**Comment by lyc8503** [comment]
Please catch Real-time Logs for worker on dashboard.

**Comment by s7net** [comment]
![image](https://github.com/lyc8503/UptimeFlare/assets/148908703/0dbe7041-6840-4f80-a403-d41a779350b1)

**Comment by s7net** [comment]
![image](https://github.com/lyc8503/UptimeFlare/assets/148908703/ec58f74c-1f06-4a02-8342-69194aaec648)

**Comment by s7net** [comment]
https://status.tala.network/

**Comment by s7net** [comment]
{
  "outcome": "exceededCpu",
  "scriptName": "uptimeflare_worker",
  "diagnosticsChannelEvents": [],
  "exceptions": [],
  "logs": [
    {
      "message": [
        "Running scheduled event on SLC..."
      ],
      "level": "log",
      "timestamp": 1704537652372
    },
    {
      "message": [
        "[SLC] Checking Germany-1..."
      ],
      "level": "log",
      "timestamp": 1704537652440
    },
    {
      "message": [
        "Germany-1 connected to de1.point.talanetwork.eu.org:22"
      ],
      "level": "log",
      "timestamp": 1704537652732
    },
    {
      "message": [
        "[SLC] Checking France-1..."
      ],
      "level": "log",
      "timestamp": 1704537652732
    },
    {
      "message": [
        "France-1 connected to de2.point.talanetwork.eu.org:22"
      ],
      "level": "log",
      "timestamp": 1704537653006
    },
    {
      "message": [
        "[SLC] Checking Italy-1..."
      ],
      "level": "log",
      "timestamp": 1704537653006
    },
    {
      "message": [
        "Italy-1 connected to de3.point.talanetwork.eu.org:22"
      ],
      "level": "log",
      "timestamp": 1704537653312
    },
    {
      "message": [
        "[SLC] Checking swdeen-1..."
      ],
      "level": "log",
      "timestamp": 1704537653312
    },
    {
      "message": [
        "swdeen-1 connected to de4.point.talanetwork.eu.org:22"
      ],
      "level": "log",
      "timestamp": 1704537653628
    },
    {
      "message": [
        "[SLC] Checking netherlands-1..."
      ],
      "level": "log",
      "timestamp": 1704537653628
    },
    {
      "message": [
        "netherlands-1 connected to nl1.point.talanetwork.eu.org:22"
      ],
      "level": "log",
      "timestamp": 1704537653930
    },
    {
      "message": [
        "[SLC] Checking netherlands-2..."
      ],
      "level": "log",
      "timestamp": 1704537653930
    },
    {
      "message": [
        "netherlands-2 connected to de5.point.talanetwork.eu.org:22"
      ],
      "level": "log",
      "timestamp": 1704537654204
    },
    {
      "message": [
        "[SLC] Checking United-Kingdom-1..."
      ],
      "level": "log",
      "timestamp": 1704537654204
    }
  ],
  "eventTimestamp": 1704537652361,
  "event": {
    "cron": "*/2 * * * *",
    "scheduledTime": 1704537652000
  },
  "id": 1
}

**Comment by lyc8503** [comment]
Your server `United-Kingdom-1` seems down and the worker failed to handle this correctly. Now the latest version should work.

You can update your repo and test again.
