### ISSUE TITLE
JSON API

### ISSUE THREAD

**Issue by covuk** [lyc8503/UptimeFlare#40]
Like [cState](https://github.com/cstate/cstate) , they have 2 options for that :  a [dot indicator](https://github.com/cstate/html-embed?tab=readme-ov-file#first-ui-dot-indicator) and an [alert box](https://github.com/cstate/html-embed?tab=readme-ov-file#second-ui-alert-box)

**Comment by lyc8503** [comment]
The indicator needs to be integrated into the user's web page, so shouldn't the user write the code for it?

I think I can add a new API for this (for getting the status in JSON).

**Comment by lyc8503** [comment]
Implemented in d8520f4

Docs: https://github.com/lyc8503/UptimeFlare/wiki/Fetch-data-in-JSON-format
