### ISSUE TITLE
部署问题：Type error: Property 'tooltip' does not exist on type '{ id: string; name: string; method: string; target: string; }'.

### ISSUE THREAD

**Issue by HanSanCoder** [lyc8503/UptimeFlare#41]
github actions 部署出现Type error: Property 'tooltip' does not exist on type '{ id: string; name: string; method: string; target: string; }'.问题。`tooltip`和`statusPageLink`没在配置文件添加，都注释后，才能正常部署。
![image](https://github.com/lyc8503/UptimeFlare/assets/118177361/28897605-4711-4071-a1e8-444985baab70)

**Comment by lyc8503** [comment]
确实存在这个 BUG，之后会修复一下。

**Comment by wuyuhanzijin** [comment]
@lyc8503 错误是由于配置的时候，如果没有设置 `tooltip` 和 `statusPageLink` ，那么就无法查询到这两个参数的值而导致的，只需要要求所有用户使用配置文件的时候，都设置` `tooltip` 和 `statusPageLink` 就可以规避这个错误了

**Comment by lyc8503** [comment]
> @lyc8503 错误是由于配置的时候，如果没有设置 `tooltip` 和 `statusPageLink` ，那么就无法查询到这两个参数的值而导致的，只需要要求所有用户使用配置文件的时候，都设置` `tooltip`和`statusPageLink` 就可以规避这个错误了

我知道，设置 `tooltip` 和 `statusPageLink` 确实不会出现问题，但这两个配置应该是可选项，用户应该可以选择删去它们，这种情况下也不应该发生错误。最近学校的事情有点忙，之后有时间我会统一修复下现有的 issues。

**Comment by VrianCao** [comment]
我也遇到了同样的问题，这使得`tooltip`和`statusPageLink`变成了必须填写的参数

**Comment by lyc8503** [comment]
> 我也遇到了同样的问题，这使得`tooltip`和`statusPageLink`变成了必须填写的参数

暂时可以通过填写空字符串 '' 解决

**Comment by lyc8503** [comment]
已经解决, 更新后应该可以不用填写这些参数了, 感谢你们汇报的 issue.
