### ISSUE TITLE
🔄Want to add automatic refresh function希望添加自动刷新功能

### ISSUE THREAD

**Issue by wkk-dev** [lyc8503/UptimeFlare#42]
🔄希望添加10s or 30s自动刷新功能
🔄Want to add 10s or 30s automatic refresh function

**Comment by lyc8503** [comment]
30s 就刷新一次会不会有些太激进了（状态最快一分钟更新一次，一般都得三分钟更新一次），不过可以添加一个三或五分钟自动刷新的功能。

**Comment by wkk-dev** [comment]
可以啊

**Comment by lyc8503** [comment]
62ba220 中实现了每五分钟自动刷新一次页面内容，同时实现了会实时更新的计时

**Comment by lyc8503** [comment]
你可以参考 Wiki 进行更新
