### ISSUE TITLE
设置检测频率

### ISSUE THREAD

**Issue by willow-god** [lyc8503/UptimeFlare#44]
您好，尊敬的开发者，请问每个检测器可以自定义检测的频率吗？我看现在好像是一分钟一次，会不会有点太频繁了呀？
![image](https://github.com/lyc8503/UptimeFlare/assets/93815242/6f6b6c80-19dc-4e51-ac95-a7ffb874d726)
并且前面还好好的，后面慢慢变卡了，请问这个可能是因为什么呀？

**Comment by lyc8503** [comment]
暂时没有自定义检测频率的功能, 具体有什么需要自定义频率的场景吗? 一分钟一次对于大部分服务应该不能造成任何实际的压力.

途中后续变卡的原因很可能是, Cloudflare Workers 会自动调度到不同地区. (鼠标移到折线图上可以看到对应发起探测的地区)
如果你的服务器在中国大陆, 从某些地区的连接性不佳, 就可能导致你图中的这种情况.

这有两种解决方法:
1. 优化你服务器的国际互联或使用 CDN. 这可以切实提升全球其他地区用户的使用体验.
2. 如果你的服务只需对中国大陆或其他某个特定地区用户提供服务, 你可以遵循 https://github.com/lyc8503/UptimeFlare/wiki/Geo-specific-checks-setup 的说明, 指定一个探测点, 防止延迟的波动.

我演示站 https://status.lyc8503.net/ 中的 HomeLab, Aliyun 等服务就使用方法 2 指定了地区.

**Comment by willow-god** [comment]
> 暂时没有自定义检测频率的功能, 具体有什么需要自定义频率的场景吗? 一分钟一次对于大部分服务应该不能造成任何实际的压力.
> 
> 途中后续变卡的原因很可能是, Cloudflare Workers 会自动调度到不同地区. (鼠标移到折线图上可以看到对应发起探测的地区) 如果你的服务器在中国大陆, 从某些地区的连接性不佳, 就可能导致你图中的这种情况.
> 
> 这有两种解决方法:
> 
> 1. 优化你服务器的国际互联或使用 CDN. 这可以切实提升全球其他地区用户的使用体验.
> 2. 如果你的服务只需对中国大陆或其他某个特定地区用户提供服务, 你可以遵循 https://github.com/lyc8503/UptimeFlare/wiki/Geo-specific-checks-setup 的说明, 指定一个探测点, 防止延迟的波动.
> 
> 我演示站 https://status.lyc8503.net/ 中的 HomeLab, Aliyun 等服务就使用方法 2 指定了地区.

好的，感谢开发者的回复！我去试试！谢谢！
