### ISSUE TITLE
部署到CF无法正常打开

### ISSUE THREAD

**Issue by pengchangg** [lyc8503/UptimeFlare#51]
页面显示
![image](https://github.com/user-attachments/assets/afed8770-7df3-48c6-bfac-f0cdd015bde6)
github actions error
![image](https://github.com/user-attachments/assets/61316241-c5d4-431a-b6dc-c98404f00476)
完整日志
[0_build-and-deploy.txt](https://github.com/user-attachments/files/16279227/0_build-and-deploy.txt)

尝试：
删除 CF 中的 UptimeFlare 相关 worker 和 KV 重新部署无效，项目目前公开你可以看我repo中的具体执行情况，谢谢🙏

**Comment by lyc8503** [comment]
感谢你的问题汇报，根据日志来看，似乎你的部署还是存在一些不一致的情况，前端页面的报错也是因为部署失败导致的。

你确定你完全删除了 UptimeFlare 相关的所有资源了吗？你应该先删除 UptimeFlare 的 KV 存储，再删除 UptimeFlare 的一个 Pages 项目和一个 Worker 项目，共三个。报错日志中似乎表明，你存在一个名为 uptimeflare_worker 的 Worker 项目并未删除，导致了命名冲突。

请你尝试再次删除上述资源后，重新提交一下任意内容，触发新的部署，看看问题是否依旧存在。

**Comment by pengchangg** [comment]
我按照 `先删除 UptimeFlare 的 KV 存储，再删除 UptimeFlare 的一个 Pages 项目和一个 Worker 项目，共三个` 这个操作之后重新出发部署成功了，我记得我昨天是全部清除过才部署的（搞得我有点怀疑自己），不过无所谓问题解决了。谢谢🙏

**Comment by lyc8503** [comment]
> 我按照 `先删除 UptimeFlare 的 KV 存储，再删除 UptimeFlare 的一个 Pages 项目和一个 Worker 项目，共三个` 这个操作之后重新出发部署成功了，我记得我昨天是全部清除过才部署的（搞得我有点怀疑自己），不过无所谓问题解决了。谢谢🙏

Cloudflare 有个前端界面的小 BUG，如果先删除了 Pages 和 Worker 似乎就不会显示 KV 的页面，实际上 KV 还会存在。你可能遇到了类似的 Bug，能运行就好😂

**Comment by pengchangg** [comment]
貌似有个新问题，我部署好了之后 更改配置文件 重新触发部署流程就会报错说同名kv已存在，我现在是删除掉CF上面的东西重新开始配置的，我看了一圈wiki没发现相关内容

**Comment by lyc8503** [comment]
没关系的，只有第一次部署流程使用了 Terraform，之后的流程中，Terraform 报错是预期行为，只要 GitHub Actions 的总体结果是通过（绿色勾），部署就应该是成功的，你可以忽略那个错误。
