### ISSUE TITLE
Show date in the popup?

### ISSUE THREAD

**Issue by EthraZa** [lyc8503/UptimeFlare#54]
There is an incident at some point in time. How do I know the date?

- Is it possible to add the date to popups? 
- Is it possible to fire up this popups on click/touch so I can see it on mobile?
* In other words, is it possible to make the bars popup to be more like the graph popup? Maybe even adding a list of the locations used that day.

![Captura de tela de 2024-07-22 15-11-38](https://github.com/user-attachments/assets/d89a70d7-7b8b-4422-8c91-ab28d1795908)

**Comment by EthraZa** [comment]
I was taking a look at the code and guess that:

- Add `<div>{incidentEnd}</div>` (or something like that) to Tooltip label.
- Add `events={{ hover: true, focus: true, touch: true }}` prop to Tooltip to enable keyboard and touch navigation.

Did I get close?

**Comment by lyc8503** [comment]
Thanks for the issue and solution! I think the second point is correct, I forgot about touchscreen support at first.

As for the first point, my plan at first was to make a separate page showing the history of the incident, where the user can browse all the history of the incident in a timeline, so I didn't add much information to this Tooltip. BTW, Displaying `incidentEnd` directly is not always correct, because each cell represents a day, but an incident may span many days (`incidentEnd` is not necessarily on the same day)

**Comment by EthraZa** [comment]
Ok, I have added the touch event and date to tooltip. Now I can open it from my phone and know the date of the bar I'm looking at.

The only thing I would like to improve, if possible, is: 
The date is beeing formated, looks like, to the worker locale (en). Do you know if there there is an easy way to set [moment locale](https://momentjs.com/docs/#/i18n/) to browser's [navigator.language](https://developer.mozilla.org/docs/Web/API/NavigatorLanguage/language) or something like that?

Anyways here is the already working implementation:
![Captura de tela de 2024-07-23 15-20-08](https://github.com/user-attachments/assets/14d9838b-98a1-4d95-bd46-7925bbb46e18)

Updated code to [DetailBar.tsx](https://github.com/lyc8503/UptimeFlare/blob/main/components/DetailBar.tsx):
```
<Tooltip
        multiline
        events={{ hover: true, focus: true, touch: true }}
        key={i}
        label={
          Number.isNaN(Number(dayPercent)) ? (
            'No Data'
          ) : (
            <>
              <div>{dayPercent + '% uptime at ' + moment(dayStart * 1000).format('L')}</div>
              {dayDownTime > 0 && (
                <div>{`Down for ${moment.preciseDiff(moment(0), moment(dayDownTime * 1000))}`}</div>
              )}
              {/* TODO: lantency detail for each bar */}
            </>
          )
        }
      >
```
I can send a PR if you are willing to accept this small updates. :)

**Comment by lyc8503** [comment]
Sorry for the delay in replying, I've implemented this feature, thanks!

You can actually convert a timestamp to a date string by using the method provided by `Date()`, which you can see here 79ea2fb. This way it should follow the locale setting of the browser.
