### ISSUE TITLE
Chart Y axe spikes

### ISSUE THREAD

**Issue by EthraZa** [lyc8503/UptimeFlare#56]
When the ordinary response time is about 20 to 100 or even 200ms, the chart is still ok, but when it spikes to 3000ms+ in the Y axe, the rest of X axe becomes just a line with small ondulations.

![Captura de tela de 2024-07-24 11-59-44](https://github.com/user-attachments/assets/7c87daa2-55c1-48b8-a646-c9fedaf02cfe)

What can be done...
As you can see in [this example](https://stackoverflow.com/questions/59823030/chart-js-compress-vertical-axis-on-barchart), Chart.js has a [logarithmic](https://www.chartjs.org/docs/latest/axes/cartesian/logarithmic.html) type that could "fix" that spikes on chart.

![download](https://github.com/user-attachments/assets/da80fd14-1733-4539-b047-e5abd134670e)

But, since the [react-chartjs-2](https://github.com/reactchartjs/react-chartjs-2/tree/master)  looks like is abandoned and the docs are not working, I can't figure out how to apply this option to chart using it, if even possible.

**Comment by lyc8503** [comment]
Personally, I think such spikes do represent timeouts or access delays occurring during probing, and we don't really need to use logarithmic units here, logarithmic units may rather confuse others. (Though maybe adding a separate config item to enable logarithmic units would also be ok, I'm not really sure)

If your service latency is generally very low, you could try lowering the timeout in your configuration, which would prevent very high spikes from affecting the chart.

**Comment by EthraZa** [comment]
If I set a low timeout it would show as a fail when it could respond, don't?
It could be an option for each monitor to enable logarithmic, maybe.

**Comment by lyc8503** [comment]
Sorry, I still don't think it makes sense to use logarithmic axes for time. This seems rather misleading, so I wouldn't make it an official option. You can modify the chart in `components/DetailChart.tsx` in your own deployment if you want.

As for the documentation for react-chartjs-2, someone has deployed an unofficial version of it themselves, so you can check that out. https://github.com/reactchartjs/react-chartjs-2/issues/1219#issuecomment-2206597972

For anyone else reading this, I'd still recommend lowering down the timeout, if your service does tend to respond quickly.
