### ISSUE TITLE
为什么不给页面添加语言切换？

### ISSUE THREAD

**Issue by wuyuhanzijin** [lyc8503/UptimeFlare#57]
切换英文和中文这是个更好的功能，这更加人性化

**Comment by lyc8503** [comment]
暂时没有 i18n 的打算, 主要出于以下考量:

1. 页面上实际的文本内容很少, 都是一些简单的英文, 意思直白, 且配有图标, 不翻译几乎不会影响用户理解.
2. i18n 需要维护中文英文在内的多种语言文件, 较为繁琐.

**Comment by lyc8503** [comment]
已经在最新版添加支持
