### ISSUE TITLE
[feat request] Clickable link identifier | 可点击链接标识

### ISSUE THREAD

**Issue by Weidows** [lyc8503/UptimeFlare#58]
![image](https://github.com/user-attachments/assets/5518e916-8731-4c53-be18-d31b7f86be1f)

如图中的 "homepage" 设置了链接也是普通文本的样式

如果能 `加一个Icon图标 / 更改字体颜色 / 下划线` 这种样式会好辨识一些, 不然确实是看不出来是不是超链接

**Comment by lyc8503** [comment]
因为添加的是 Tooltip, Tooltip 本身里面写的并不一定是个超链接, 所以一开始没做超链接的样式.

这个确实可以添加一下~

**Comment by lyc8503** [comment]
哦, 又看了下, 当时是故意把下划线样式去掉的, 当时我可能是觉得不一致不太美观, ~~现在加回来看看也还好, 就加回来了~~.
