### ISSUE TITLE
如何排查notification不工作的问题

### ISSUE THREAD

**Issue by Frankcsc** [lyc8503/UptimeFlare#59]
尊敬的作者，您好，我在使用中对notification进行了如下配置

```
  notification: {
    appriseApiServer: "https://push-sta**********jects.vercel.app/notify",
    recipientUrl: "tgram://67******37:AAF**********j4/52*****06",
    timeZone: "Asia/Shanghai",
    gracePeriod: 5,
  },
```

vercel的通知链接可以正常访问，浏览器访问后显示：Apprise Vercel is working, use POST method to send notifications.
tg配置行前半部分是机器人key，后半部分无论是换成我自己的tg用户id（已私聊机器人）还是群组（已将机器人设置为管理员）id，都没有受到过任何被监控网站的宕机通知。（宕机时长达1h）

请问何种情况下才会触发通知？以及如何排查通知不工作的问题？

谢谢！

**Comment by lyc8503** [comment]
看起来配置没有明显的问题, 如需要测试你的配置, 请你在自己的机器上运行以下 curl 命令, 看看是否能收到消息.

注意 vercel 默认的 `vercel.app` 在大陆地区可能已经无法访问, 你可能需要使用代理或境外的机器进行测试.

```
curl -X POST https://***.vercel.app/notify -H 'Content-Type: application/json' --data '{"body": "Hello!", "urls": "tgram://64***97:AA*******U/18****9"}'
```

如果发生错误, 你可以尝试查看下 Vercel 的实时日志.

**Comment by Frankcsc** [comment]
您好，我的问题解决了，是因为用错了vercel链接导致了一个重定向的问题。谢谢！

**Comment by pothi** [comment]
Thanks for creating this question and for the answer. I used the deployment URL from vercel instead of the domain URL. My bad. Anyway, fixed it and got the notification working after seeing this QA. Thanks again to both.
