### ISSUE TITLE
怎么自定义cron和发送email？

### ISSUE THREAD

**Issue by ltxlong** [lyc8503/UptimeFlare#60]
想每小时监控一次，直接修改deploy.tf和在action里面直接cp命令？并且不想再部署vercel就可以发送email

**Comment by lyc8503** [comment]
> 想每小时监控一次，直接修改deploy.tf和在action里面直接cp命令？

目前不支持修改 CRON 的时间间隔, 会有其他比较多地方受到影响, 对于绝大部分服务, 一分钟一次的监控应该不会造成任何压力.

> 并且不想再部署vercel就可以发送email

这在 Cloudflare 平台上目前是不可能的, Cloudflare Workers 禁止了邮件相关的端口. 如果你不想部署 Vercel, 可以考虑在配置文件中自定义 Webhook, 推送到你需要的平台.
