### ISSUE TITLE
Reached 50% of the daily usage limit for Cloudflare Workers KV operations

### ISSUE THREAD

**Issue by Youngv** [lyc8503/UptimeFlare#63]
![image](https://github.com/user-attachments/assets/c8d528f0-2469-4b97-8b1f-48318e5969c9)
Recently, I have received numerous emails from Cloudflare notifying me that I have reached 50% of the daily usage limit for Cloudflare Workers KV operations. I only have one project utilizing KV; is this normal?

**Comment by lyc8503** [comment]
Yes, this is normal. This project uses 500+ KV writes per day, while the free tier for Cloudflare workers is 1000 KV Write/day. You can safely ignore this warning, or you can delete these warning emails using Gmail keyword filters.

Maybe in a future version we will turn to Cloudflare D2 for database, which has a much higher free tier.

**Comment by Yi-Program** [comment]
请问，目前有没有办法对于KV的操作数，降低写入频率

---

*Is there any way to reduce the write frequency for the number of KV operations?*

**Comment by lyc8503** [comment]
If you change the value of `kvWriteCooldownMinutes` in the config file to a larger value, you should be able to reduce the write counts, and at the same time, the `Last updated` time displayed on the front-end page may be updated more slowly.

In the absence of an incident, the amount of writes used in a day should be equal to `60 * 24 / kvWriteCooldownMinutes`. An incident may result in additional writes.

**Comment by lyc8503** [comment]
`kvWriteCooldownMinutes` default 3 minutes should already be a long time, and I personally wouldn't recommend modifying it to a longer interval. If you are really concerned about write usage, you should also choose a value of less than 10 minutes.
