### ISSUE TITLE
可以部署在云服务器上吗

### ISSUE THREAD

**Issue by atom077** [lyc8503/UptimeFlare#68]

**Comment by lyc8503** [comment]
暂时还不行，之前有个 issue 讨论 selfhost 的可能，但目前还没实现。Docker 部署也会导致失去本项目重要特性之一：指定地点发起监测。

为了方便，暂时 close，后续讨论可移步 https://github.com/lyc8503/UptimeFlare/issues/22

**Comment by lyc8503** [comment]
Reopened in #157
