### ISSUE TITLE
请求新增 Webhook 支持

### ISSUE THREAD

**Issue by AkarinLiu** [lyc8503/UptimeFlare#72]
原因：飞书的自定义机器人支持 Webhook

**Comment by lyc8503** [comment]
Hi, 目前本项目支持两种方式:
1. 通过 Apprise 发送通知，其中支持飞书，参考：https://github.com/lyc8503/UptimeFlare/wiki/Setup-notification#apprise 以及 https://github.com/caronc/apprise/wiki/Notify_feishu
2. 自己在配置中写自定义的 Webhook 回调，参考：https://github.com/lyc8503/UptimeFlare/wiki/Setup-notification#custom-webhook-only-for-javascript-developers-advanced

应该能满足你飞书机器人发送通知的需求，如果你有更多需求可以补充。
