### ISSUE TITLE
checkLocationWorkerRoute Error

### ISSUE THREAD

**Issue by komiratsu192** [lyc8503/UptimeFlare#79]
I read [this wiki](https://github.com/lyc8503/UptimeFlare/wiki/Geo-specific-checks-setup) and did as the wiki said.
when i visit worker domain(jp.blahblah.blah), it returns `Remote worker is working...` but when i wrote that url to config file, an error occured.

So i found the Worker Logs and found this message, `Error calling worker: SyntaxError: Unexpected token 'e', "error code: 1002" is not valid JSON`

I also read #75 so changed the ip, but it didn't work.
What can i do now?

**Comment by komiratsu192** [comment]
Ah, i want to use `checkLocationWorkerRoute` with HTTP monitor.
Does `checkLocationWorkerRoute` work with both HTTP and TCP monitor?

**Comment by lyc8503** [comment]
This works on both TCP and HTTP. It looks like a recent Cloudflare update in grayscale for Workers caused this issue. I'll try to fix it once Cloudflare stabilizes. (Currently, it appears that selecting some target regions causes an error code of 1002. Maybe you'll have to leave this feature disable for a while.)

**Comment by komiratsu192** [comment]
Thank you for fast respond. I'm gonna disable this feature.

**Comment by komiratsu192** [comment]
Just keep this in mind
if i set worker URL and visit that page, it returns `Remote worker is working...` but also returns 405 error.
```
request URL:
https://blah.blah/
Request Method: GET
Status Code: 405 Method Not Allowed
```
Used a developer console.

**Comment by lyc8503** [comment]
> Just keep this in mind if i set worker URL and visit that page, it returns `Remote worker is working...` but also returns 405 error.
> 
> ```
> request URL:
> https://blah.blah/
> Request Method: GET
> Status Code: 405 Method Not Allowed
> ```
> 
> Used a developer console.

405 is expected here. We use `POST` to acutally send a request.

**Comment by komiratsu192** [comment]
well i changed option from GET to POST but it doesnt work

**Comment by lyc8503** [comment]
> well i changed option from GET to POST but it doesnt work

Don't worry, we also need to pass specific parameters for it to work. Actually we can't test it this way, it's always working if we are testing it directly from Internet. This is caused by some magic Cloudflare internal mechanism.

**Comment by rrandom** [comment]
I met the same 1002 error too, when i try to visit the fetch from the cron, but using browser everything is ok. is there any workaround?

**Comment by lyc8503** [comment]
> I met the same 1002 error too, when i try to visit the fetch from the cron, but using browser everything is ok. is there any workaround?

Sorry there's so far no workarounds except trying another IP, but now Cloudflare may have completely blocked this. I'll work on a workaround for this (maybe use a custom relay server to route requests to correct region... or rely on some external platforms e.g. `vercel`, but I am not sure for now) 

You can disable geo-specific checks for now.
