### ISSUE TITLE
Configuring cloudflare pages

### ISSUE THREAD

**Issue by Faiz-Liners** [lyc8503/UptimeFlare#80]
I don't really know how to deploy this correctly.
The quickstart doesn't show what configuration need to be set on cloudflare pages.
I set the build configuration to none and it deployed successfully. But there's no content shown. Just a blank site on the cf pages.
I need help configuring the cloudflare pages.

**Comment by lyc8503** [comment]
> I don't really know how to deploy this correctly. The quickstart doesn't show what configuration need to be set on cloudflare pages. I set the build configuration to none and it deployed successfully. But there's no content shown. Just a blank site on the cf pages. I need help configuring the cloudflare pages.

I didn't quite get what do you mean. Could you post your current config file?

> The quickstart doesn't show what configuration need to be set on cloudflare pages.

This is related to the specific target you're going to monitor.
