### ISSUE TITLE
My Fileshare 指向了错误的地址 | My Fileshare points to the wrong address

### ISSUE THREAD

**Issue by Pigeonszz** [lyc8503/UptimeFlare#82]
![image](https://github.com/user-attachments/assets/80bec460-7898-444d-8fec-05a55e438d4e)

**Comment by lyc8503** [comment]
感谢你的提醒，确实，我在填写配置时写错了，已经更正😂

（这只是一个我自己站点上的配置问题，并不是项目 Bug）

![image](https://github.com/user-attachments/assets/15ba557c-a390-4395-b34e-4ee3a7fb960b)
