### ISSUE TITLE
对于非标准端口的https检测始终返回失败

### ISSUE THREAD

**Issue by shigu666** [lyc8503/UptimeFlare#83]
我创建了一个8433端口上的url检测https://api.shigu.cc:8443 ，但是始终表现为超时或525错误
![图片](https://github.com/user-attachments/assets/f22f34dc-fac5-4d06-ae69-52ccffa2754a)

**Comment by lyc8503** [comment]
这是一个已知的问题，Cloudflare 目前不支持非标端口的 HTTP/HTTPS 连接，即使你填写了端口号，也会访问到 443 端口。

你目前可能只能使用 TCP 模式检测，后续*可能*会加入自己实现的 SSL 握手，以绕过 Cloudflare 的该限制。

**Comment by shigu666** [comment]
感谢回复，建议在修复前添加到文档中
